run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - gocritic
    - gofumpt
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
        disabled: true
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
  gofumpt:
    extra-rules: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
